
[project]
name = "model_project"
version = "0.0.1"
description = "Some modeling project"

[project.optional-dependencies]
TEST = [
    "pytest",
    "pytest-cov[all]"
]

[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.setuptools.packages.find]
where = ["src"]
